Matrix Representation of Least Square Estimates

# Data

The data used is available on Kaggle. https://www.kaggle.com/joelwilson/2012-2016-presidential-elections/data

I created an abreviated version of the csv, with one outcome variable and 4 explanatory variable.

The explanatory and outcome variable were picked to be numeric. 

| Col        | Type           | Description  |
| ------------- |:-------------:| -----:|
| 1      | Outcome | Share of Trump Votes in 2016 |
| 2      | Explanatory      |  Share of county aged over 65  |
| 3 | Explanatory      |   Share of blacks in county  |
| 4 | Explanatory      |  Share of people in county with bachelors degrees   |
| 5 | Explanatory      |  Average income in county   |

Each Row represents a county.

In [87]:
from numpy import genfromtxt
my_data = genfromtxt('voteSimplified.csv', delimiter=',')
print(my_data)

[[  9.96587573e-02   1.44000000e+01   1.83000000e-01   5.89000000e+01
    6.24980000e+04]
 [  1.68881552e-01   9.30000000e+00   9.10000000e-02   7.17000000e+01
    6.20180000e+04]
 [  1.72557715e-01   1.14000000e+01   5.30000000e-02   7.44000000e+01
    5.90880000e+04]
 ..., 
 [  2.29176471e-01   7.30000000e+00   3.00000000e-03   1.24000000e+01
    1.05750000e+04]
 [  6.76022835e-01   1.28000000e+01   3.84000000e-01   8.50000000e+00
    8.94800000e+03]
 [  8.32182320e-02   6.80000000e+00   2.00000000e-03   1.18000000e+01
    8.76800000e+03]]


The first column y is the outcome variable. We need to make it's own vector

In [88]:
y = numpy.transpose(numpy.matrix(my_data[:,0]))
print(y)

[[ 0.09965876]
 [ 0.16888155]
 [ 0.17255771]
 ..., 
 [ 0.22917647]
 [ 0.67602284]
 [ 0.08321823]]


We put the explanatory variables in an array X and add a first column of 1s to the array

In [89]:
X = my_data[:,1:5]
print(X)

[[  1.44000000e+01   1.83000000e-01   5.89000000e+01   6.24980000e+04]
 [  9.30000000e+00   9.10000000e-02   7.17000000e+01   6.20180000e+04]
 [  1.14000000e+01   5.30000000e-02   7.44000000e+01   5.90880000e+04]
 ..., 
 [  7.30000000e+00   3.00000000e-03   1.24000000e+01   1.05750000e+04]
 [  1.28000000e+01   3.84000000e-01   8.50000000e+00   8.94800000e+03]
 [  6.80000000e+00   2.00000000e-03   1.18000000e+01   8.76800000e+03]]


In [90]:
import numpy
ones = numpy.ones((numpy.shape(X)[0], 1), dtype = float)
X = numpy.concatenate((ones,X),axis=1)
X = numpy.matrix(X)
print(X)

[[  1.00000000e+00   1.44000000e+01   1.83000000e-01   5.89000000e+01
    6.24980000e+04]
 [  1.00000000e+00   9.30000000e+00   9.10000000e-02   7.17000000e+01
    6.20180000e+04]
 [  1.00000000e+00   1.14000000e+01   5.30000000e-02   7.44000000e+01
    5.90880000e+04]
 ..., 
 [  1.00000000e+00   7.30000000e+00   3.00000000e-03   1.24000000e+01
    1.05750000e+04]
 [  1.00000000e+00   1.28000000e+01   3.84000000e-01   8.50000000e+00
    8.94800000e+03]
 [  1.00000000e+00   6.80000000e+00   2.00000000e-03   1.18000000e+01
    8.76800000e+03]]


Let's start by finding $\hat{\beta}$

In [92]:
import numpy.linalg
beta_hat = numpy.linalg.inv(numpy.transpose(X) * X) * numpy.transpose(X) * y
print(beta_hat)

[[  7.40014001e-01]
 [  3.15253921e-03]
 [ -4.56060410e-01]
 [ -1.09702672e-02]
 [  4.22347768e-06]]


We can then find the hat matrix
$H = X(X^TX)^{-1}X^T$

In [93]:
H = X * numpy.linalg.inv(numpy.transpose(X) * X) * numpy.transpose(X)
print(H)

[[ 0.01950196  0.01715852  0.01469296 ..., -0.00672144 -0.00515253
  -0.00772863]
 [ 0.01715852  0.01722554  0.01572578 ..., -0.00439431 -0.00440652
  -0.00509817]
 [ 0.01469296  0.01572578  0.01504994 ..., -0.00371311 -0.00388272
  -0.00423957]
 ..., 
 [-0.00672144 -0.00439431 -0.00371311 ...,  0.00547984  0.00283227
   0.00599284]
 [-0.00515253 -0.00440652 -0.00388272 ...,  0.00283227  0.00367245
   0.00318662]
 [-0.00772863 -0.00509817 -0.00423957 ...,  0.00599284  0.00318662
   0.00657607]]


Next we compute $\hat{y}$

In [94]:
y_hat = H * y
print(y_hat)

[[ 0.31976168]
 [ 0.2031946 ]
 [ 0.18515072]
 ..., 
 [ 0.67029132]
 [ 0.54978371]
 [ 0.66812145]]


We can also compute $\beta$

We can compute the residuals $\hat{\epsilon}$

In [95]:
epsilon_hat = y - y_hat
print(epsilon_hat)

[[-0.22010292]
 [-0.03431305]
 [-0.012593  ]
 ..., 
 [-0.44111485]
 [ 0.12623912]
 [-0.58490321]]


The residual sum of squares is then

In [96]:
rss = numpy.transpose(epsilon_hat) * epsilon_hat
print(rss)

[[ 40.06290365]]
